    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar PyInstaller
        run: pip install pyinstaller

      - name: Gerar executável
        run: pyinstaller --onefile quiz.py

      - name: Renomear e fazer upload (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mv dist/quiz.exe dist/pyquiz-windows.exe
          
      - name: Renomear e fazer upload (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          mv dist/quiz dist/pyquiz-linux

      - name: Renomear e fazer upload (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          mv dist/quiz dist/pyquiz-macos

      - name: Upload do executável
        uses: softprops/action-gh-release@v2
        with:
          files: dist/${{ matrix.asset_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
